### ISSUE TITLE
建议两个

### ISSUE THREAD

**Issue by swordfeng** [KevinWang15/fdty#1]
- 做成userscript，这样可以直接用greasemonkey或tampermonkey插件加载
- 试试`$('#radiobutton-selector').click()`？

**Comment by crazyboycjr** [comment]
window.jQuery("#" + getRadioButtonId(questionI, answer ^ 1)).click();
亲测可用

**Comment by KevinWang15** [comment]
@swordfeng 谢谢建议！不过greasemonkey非计算机专业的同学可能玩不来呀，以及考试界面是把所有工具栏、菜单栏都隐藏掉的，我还需要在Console里打出信息，不知道可不可行。我现在考完了，系统已经进不去了…下次试试看greasemonkey
第二点…陈镜融同学已经发现了，是我程序里选反了，他们的复选框，正确的ID是xxx0xxx，错误的ID是xxx1xxx，太粗心了

**Comment by KevinWang15** [comment]
@crazyboycjr 非常感谢！你希望发Pull Request吗，还是我直接改？
