### ISSUE TITLE
出现这样的错误是为什么

### ISSUE THREAD

**Issue by oldlemon233** [KevinWang15/fdty#14]
VM171:1 Mixed Content: The page at 'https://fdtyjw.fudan.edu.cn/sportexam/stexamV1.aspx' was loaded over HTTPS, but requested an insecure script 'http://kevinwang.cc/fdty/fdty.js?1637833249549'. This request has been blocked; the content must be served over HTTPS.

**Comment by KevinWang15** [comment]
现在学校网站搞成https了？…高级，看来我需要提供一个https版本的

**Comment by KevinWang15** [comment]
部署了https，更新了README

```javascript
var fdty_src="https://kevinwang.cc/fdty/fdty.js";var f_sl = document.createElement("script");f_sl.type = "text/javascript";console.info('正在加载自动答题脚本');f_sl.src = fdty_src + '?' + (+new Date());document.getElementsByTagName("head")[0].appendChild(f_sl);
```

用这个再试一试 @oldlemon233
