### ISSUE TITLE
脚本运行报错

### ISSUE THREAD

**Issue by ArcPen** [KevinWang15/fdty#15]
![Snipaste_2021-12-13_07-49-39](https://user-images.githubusercontent.com/35322981/145735589-a1e6022c-38ab-4c36-b1be-69ff3b2fddda.png)

**Comment by ArcPen** [comment]
详细信息通过邮箱发送给你了owo

**Comment by KevinWang15** [comment]
看起来学校网站又改回http了吗？前段时间 #14 里汇报学校网站使用了https，导致使用http方式加载脚本失效，现在看来改回http了，用https方式加载脚本失效

**Comment by KevinWang15** [comment]
@ArcPen 帮忙试一下这样行不行：

```
var fdty_src="//kevinwang.cc/fdty/fdty.js";var f_sl = document.createElement("script");f_sl.type = "text/javascript";console.info('正在加载自动答题脚本');f_sl.src = fdty_src + '?' + (+new Date());document.getElementsByTagName("head")[0].appendChild(f_sl);
```

这种写法是自适应http或https的

**Comment by Shimingyi** [comment]
@KevinWang15 It works well, thanks!

**Comment by KevinWang15** [comment]
好的，我更新了README，都用这种写法了
