### ISSUE TITLE
回应PR请求-单选题html

### ISSUE THREAD

**Issue by EICr** [KevinWang15/fdty#4]
<div id="Panel1">
	
							
									<font class="fonttitle">单项选择题
										(基础题每题0分,共0题，专项题每题2分,共10题)
										<br>
									</font>
								
									1
									.
									正式排球比赛成年男子网高（）m。
									<br>
									<table id="repSin_RadioButtonList1_0" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_0_0_0">A.2.24</label><input id="repSin_RadioButtonList1_0_0_0" type="radio" name="repSin$ctl01$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_0_1_0">B.2.34</label><input id="repSin_RadioButtonList1_0_1_0" type="radio" name="repSin$ctl01$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_0_2_0">C.2.35</label><input id="repSin_RadioButtonList1_0_2_0" type="radio" name="repSin$ctl01$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_0_3_0">D.2.43</label><input id="repSin_RadioButtonList1_0_3_0" type="radio" name="repSin$ctl01$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									2
									.
									公园排球比赛场地为（）
									<br>
									<table id="repSin_RadioButtonList1_1" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_1_0_1">A.长13.4米宽6.1米</label><input id="repSin_RadioButtonList1_1_0_1" type="radio" name="repSin$ctl02$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_1_1_1">B.长6.7米宽6.1米</label><input id="repSin_RadioButtonList1_1_1_1" type="radio" name="repSin$ctl02$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_1_2_1">C.长13米宽6米</label><input id="repSin_RadioButtonList1_1_2_1" type="radio" name="repSin$ctl02$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_1_3_1">D.长7.5米宽6.1米</label><input id="repSin_RadioButtonList1_1_3_1" type="radio" name="repSin$ctl02$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									3
									.
									下列准备姿势中，最常用、最基本的是（）。
									<br>
									<table id="repSin_RadioButtonList1_2" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_2_0_2">A.稍蹲</label><input id="repSin_RadioButtonList1_2_0_2" type="radio" name="repSin$ctl03$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_2_1_2">B.半蹲</label><input id="repSin_RadioButtonList1_2_1_2" type="radio" name="repSin$ctl03$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_2_2_2">C.低蹲</label><input id="repSin_RadioButtonList1_2_2_2" type="radio" name="repSin$ctl03$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_2_3_2">D.深蹲</label><input id="repSin_RadioButtonList1_2_3_2" type="radio" name="repSin$ctl03$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									4
									.
									那个项目是我校传统体育项目
									<br>
									<table id="repSin_RadioButtonList1_3" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_3_0_3">A.击剑</label><input id="repSin_RadioButtonList1_3_0_3" type="radio" name="repSin$ctl04$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_3_1_3">B.羽毛球</label><input id="repSin_RadioButtonList1_3_1_3" type="radio" name="repSin$ctl04$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_3_2_3">C.乒乓</label><input id="repSin_RadioButtonList1_3_2_3" type="radio" name="repSin$ctl04$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_3_3_3">D.排球</label><input id="repSin_RadioButtonList1_3_3_3" type="radio" name="repSin$ctl04$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									5
									.
									正式排球比赛成年女子网高（）m。
									<br>
									<table id="repSin_RadioButtonList1_4" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_4_0_4">A.2.24</label><input id="repSin_RadioButtonList1_4_0_4" type="radio" name="repSin$ctl05$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_4_1_4">B.2.34</label><input id="repSin_RadioButtonList1_4_1_4" type="radio" name="repSin$ctl05$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_4_2_4">C.2.35</label><input id="repSin_RadioButtonList1_4_2_4" type="radio" name="repSin$ctl05$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_4_3_4">D.2.43</label><input id="repSin_RadioButtonList1_4_3_4" type="radio" name="repSin$ctl05$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									6
									.
									参加公园排球的年龄限制为（）岁
									<br>
									<table id="repSin_RadioButtonList1_5" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_5_0_5">A.50</label><input id="repSin_RadioButtonList1_5_0_5" type="radio" name="repSin$ctl06$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_5_1_5">B.55</label><input id="repSin_RadioButtonList1_5_1_5" type="radio" name="repSin$ctl06$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_5_2_5">C.60</label><input id="repSin_RadioButtonList1_5_2_5" type="radio" name="repSin$ctl06$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_5_3_5">D.没有限制</label><input id="repSin_RadioButtonList1_5_3_5" type="radio" name="repSin$ctl06$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									7
									.
									拦网的技术动作要点表述错误的是
									<br>
									<table id="repSin_RadioButtonList1_6" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_6_0_6">A.正面对网</label><input id="repSin_RadioButtonList1_6_0_6" type="radio" name="repSin$ctl07$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_6_1_6">B.跨步或交叉步移动</label><input id="repSin_RadioButtonList1_6_1_6" type="radio" name="repSin$ctl07$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_6_2_6">C.手臂在本方场区，不能过网</label><input id="repSin_RadioButtonList1_6_2_6" type="radio" name="repSin$ctl07$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_6_3_6">D.提肩伸向对方场区</label><input id="repSin_RadioButtonList1_6_3_6" type="radio" name="repSin$ctl07$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									8
									.
									普通暂停的时间为（）秒。
									<br>
									<table id="repSin_RadioButtonList1_7" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_7_0_7">A.30</label><input id="repSin_RadioButtonList1_7_0_7" type="radio" name="repSin$ctl08$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_7_1_7">B.60</label><input id="repSin_RadioButtonList1_7_1_7" type="radio" name="repSin$ctl08$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_7_2_7">C.90</label><input id="repSin_RadioButtonList1_7_2_7" type="radio" name="repSin$ctl08$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_7_3_7">D.120</label><input id="repSin_RadioButtonList1_7_3_7" type="radio" name="repSin$ctl08$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									9
									.
									裁判鸣哨（）秒内的发球为有效发球。
									<br>
									<table id="repSin_RadioButtonList1_8" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_8_0_8">A.4</label><input id="repSin_RadioButtonList1_8_0_8" type="radio" name="repSin$ctl09$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_8_1_8">B.6</label><input id="repSin_RadioButtonList1_8_1_8" type="radio" name="repSin$ctl09$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_8_2_8">C.8</label><input id="repSin_RadioButtonList1_8_2_8" type="radio" name="repSin$ctl09$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_8_3_8">D.10</label><input id="repSin_RadioButtonList1_8_3_8" type="radio" name="repSin$ctl09$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
									10
									.
									扣球要领表述不正确的是
									<br>
									<table id="repSin_RadioButtonList1_9" cellpadding="10">
		<tbody><tr>
			<td><label for="repSin_RadioButtonList1_9_0_9">A.挥臂鞭打动作</label><input id="repSin_RadioButtonList1_9_0_9" type="radio" name="repSin$ctl10$RadioButtonList1" value="A"></td><td><label for="repSin_RadioButtonList1_9_1_9">B.三步助跑连贯不能有停顿</label><input id="repSin_RadioButtonList1_9_1_9" type="radio" name="repSin$ctl10$RadioButtonList1" value="B"></td>
		</tr><tr>
			<td><label for="repSin_RadioButtonList1_9_2_9">C.最佳击球点是头顶上方</label><input id="repSin_RadioButtonList1_9_2_9" type="radio" name="repSin$ctl10$RadioButtonList1" value="C"></td><td><label for="repSin_RadioButtonList1_9_3_9">D.手腕有推压动作</label><input id="repSin_RadioButtonList1_9_3_9" type="radio" name="repSin$ctl10$RadioButtonList1" value="D"></td>
		</tr>
	</tbody></table>
								
						
</div>

**Comment by EICr** [comment]
对此一窍不通，照着PR请求里的指南瞎弄了一通，如果有其他需求请及时联系，下周还可以进入考试
——来自一只电脑废
感激up的工作和分享！

**Comment by KevinWang15** [comment]
@EICr 感谢提供的资料，我在这份资料的基础上实现了单选题自动勾选，在测试页面中测试通过啦~ 如果你方便的话，可以再到考试系统中，试试看在真实考试系统里这个新功能是否正常工作。还有就是主页的程序截图有一点旧了，方便的话截一下新的运行时的图片给我，谢谢啦

**Comment by KevinWang15** [comment]
@EICr 补充一下，我是想更新下readme里的第一和第四张截图，所以你能帮你的话，就把chrome命令行里的

**Comment by KevinWang15** [comment]
@EICr 补充一下，我是想更新下readme里的第一和第四张截图，所以你能帮你的话，就把chrome命令行里的所有输出截图给我就好(包括你输入的那行命令)，命令行窗口拉大一些，这样大多数题目都能显示在一行里，效果好。你只要截完整，后面拼接等工作我自己用PS处理啦

**Comment by KevinWang15** [comment]
单选题自动做题功能已验证
