### ISSUE TITLE
体教部网站反转了正确和错误的选项位置

### ISSUE THREAD

**Issue by bernardshen** [KevinWang15/fdty#6]
如题，第一次提交得了两分，只对了一道没有匹配到的题目。

**Comment by ichn-hu** [comment]
凉凉

**Comment by KevinWang15** [comment]
@bernardshen 感谢反馈本问题，系统的确做了修改
现在是非题自动勾选功能已经修复，
单选题我看不到，不知道是否有做修改，如果有同学看到了请贴一份html代码给我

**Comment by strangepusai** [comment]
差点狗带，居然随机了。。。

**Comment by KevinWang15** [comment]
魔高一尺，道高一丈啊哈哈

**Comment by KevinWang15** [comment]
现在是非题/单选题自动勾选均已恢复正常
