### ISSUE TITLE
无法自动完成选择题

### ISSUE THREAD

**Issue by j7168908jx** [KevinWang15/fdty#9]
自动填充现在好像无法自动完成单项选择题？（判断题可以正常完成）

**Comment by j7168908jx** [comment]
在检测题目时就只能检测到判断题的存在...
![_20181203124110](https://user-images.githubusercontent.com/29114306/49353470-d8895000-f6f8-11e8-8aab-880ffaa52f02.png)

**Comment by KevinWang15** [comment]
@j7168908jx 帮忙存一份考卷的HTML，发我研究一下 我现在已经毕业了所以进不去这个系统了

**Comment by KevinWang15** [comment]
@j7168908jx 感谢~现在的考卷结构稍有不一样，已经修复，可以自动选选择题啦

**Comment by j7168908jx** [comment]
然而好像还是匹配不上诶...刚刚又试了一次

**Comment by KevinWang15** [comment]
是一样的HTML上吗？你发给我的HTML，我存成了 https://github.com/KevinWang15/fdty/blob/master/testpage2.html

原本这个文件上不行的，我现在验证已经行了

另外，是从项目主页步骤4中复制粘贴的最新代码吗

**Comment by j7168908jx** [comment]
解决啦，大家记得清理一下缓存...新代码好像当时直接被用缓存了...

**Comment by KevinWang15** [comment]
有可能，我晚上加一个querystring来禁一下缓存吧

**Comment by KevinWang15** [comment]
缓存问题已经解决，感谢提出
